/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a trusted observer report. */
        post: operations["submitReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current reconciled topology. */
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream topology invalidations over server-sent events. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return recent traffic buckets and path events for an edge. */
        get: operations["getEdgeHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Normal observer messages contain observers. relay_session_update contains relaySessions instead; the server rejects envelopes that mix the two forms. */
        ReportEnvelope: {
            /** @constant */
            version: 1;
            /** Format: uuid */
            reportId: string;
            /** Format: uuid */
            reporterInstanceId: string;
            /** Format: int64 */
            sequence: number;
            /** Format: date-time */
            collectedAt: string;
            kind: components["schemas"]["ReportKind"];
            observers?: components["schemas"]["ObserverReport"][];
            relaySessions?: components["schemas"]["RelaySessionObservation"][];
        };
        /** @enum {string} */
        ReportKind: "observer_hello" | "inventory_update" | "traffic_sample" | "observer_heartbeat" | "relay_session_update";
        /** @description For hello and inventory_update, peers is the observer's complete current runtime peer view. For traffic_sample it is sparse and contains only peers with business byte deltas. */
        ObserverReport: {
            observer: components["schemas"]["NodeIdentity"];
            inventoryGeneration: string;
            peers?: components["schemas"]["PeerObservation"][];
        };
        /** @description At least one stableNodeId, nodeId, nodeKey, discoKey, or Tailscale IP is required. Names are display fields and never merge nodes. */
        NodeIdentity: {
            stableNodeId?: string;
            nodeId?: string;
            nodeKey?: string;
            discoKey?: string;
            hostname?: string;
            dnsName?: string;
            /** @description Reported operating system for display only; never identity evidence. */
            os?: string;
            tailscaleIps?: string[];
        };
        PeerObservation: {
            peer: components["schemas"]["NodeIdentity"];
            /** Format: int64 */
            rxBytes: number;
            /** Format: int64 */
            txBytes: number;
            /** Format: int64 */
            rxDelta: number;
            /** Format: int64 */
            txDelta: number;
            /**
             * Format: int64
             * @description Zero for hello/inventory baselines; positive for traffic samples.
             */
            sampleDurationMs: number;
            path: components["schemas"]["PathObservation"];
            /** Format: date-time */
            lastActive: string;
        };
        /** @description A Peer Relay observer's view of traffic between two Tailnet nodes. The logical edge is source-target while relay supplies third-party provenance. */
        RelaySessionObservation: {
            /** @description The relay observer; stableNodeId is required by the ingest contract. */
            relay: components["schemas"]["NodeIdentity"];
            source: components["schemas"]["NodeIdentity"];
            target: components["schemas"]["NodeIdentity"];
            sessionId: string;
            /** Format: int64 */
            vni: number;
            sourceEndpoint?: string;
            targetEndpoint?: string;
            /** Format: int64 */
            sourceToTargetBytes: number;
            /** Format: int64 */
            targetToSourceBytes: number;
            /** Format: int64 */
            sourceToTargetDelta: number;
            /** Format: int64 */
            targetToSourceDelta: number;
            /** Format: int64 */
            sampleDurationMs: number;
            /** Format: date-time */
            lastActive: string;
        };
        PathObservation: {
            kind: components["schemas"]["PathKind"];
            directEndpoint?: string;
            derpRegion?: string;
            peerRelayStableNodeId?: string;
        };
        /** @enum {string} */
        PathKind: "direct" | "derp" | "peer_relay" | "unknown";
        ReportReceipt: {
            accepted: boolean;
            resyncRequired: boolean;
            controlStableNodeIds: string[];
            /** Format: int64 */
            heartbeatIntervalMs: number;
        };
        Topology: {
            /** Format: date-time */
            generatedAt: string;
            /**
             * Format: date-time
             * @description Earliest known lifecycle deadline that can change this snapshot.
             */
            nextChangeAt?: string;
            nodes: components["schemas"]["TopologyNode"][];
            edges: components["schemas"]["TopologyEdge"][];
            observers: components["schemas"]["ObserverState"][];
        };
        TopologyNode: components["schemas"]["NodeIdentity"] & {
            id: string;
            observable: boolean;
            online: boolean;
            /** Format: date-time */
            lastEvidenceAt: string;
            clockSkewed: boolean;
        };
        TopologyEdge: {
            id: string;
            source: string;
            target: string;
            path: components["schemas"]["PathObservation"];
            /** @enum {string} */
            state: "active" | "recent";
            /** Format: double */
            aToBBytesPerSecond: number;
            /** Format: double */
            bToABytesPerSecond: number;
            /** Format: date-time */
            lastActive: string;
            observations: components["schemas"]["ObservationProvenance"][];
            conflicts?: components["schemas"]["PathObservation"][];
        };
        ObservationProvenance: {
            observerId: string;
            path: components["schemas"]["PathObservation"];
            /** Format: date-time */
            collectedAt: string;
            /** Format: date-time */
            receivedAt: string;
            clockSkewed: boolean;
        };
        ObserverState: {
            id: string;
            hostname: string;
            online: boolean;
            /** Format: date-time */
            lastSeen: string;
            /** Format: date-time */
            lastCollectedAt: string;
            /** Format: int64 */
            clockSkewMs: number;
            clockSkewed: boolean;
        };
        EdgeHistory: {
            edgeId: string;
            traffic: components["schemas"]["TrafficBucket"][];
            pathEvents: components["schemas"]["PathEvent"][];
        };
        TrafficBucket: {
            /** Format: date-time */
            bucketStart: string;
            /** Format: int64 */
            aToBBytes: number;
            /** Format: int64 */
            bToABytes: number;
        };
        PathEvent: {
            /** Format: date-time */
            observedAt: string;
            path: components["schemas"]["PathObservation"];
            observations: components["schemas"]["ObservationProvenance"][];
        };
        Problem: {
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: {
        /** @description Request failed. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submitReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportEnvelope"];
            };
        };
        responses: {
            /** @description Report accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getTopology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current topology. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topology"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getEdgeHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edge history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeHistory"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
