/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return authenticated observer protocol capabilities. */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a trusted observer report. */
        post: operations["submitReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current reconciled topology. */
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the optional control-plane device directory. */
        get: operations["getDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream topology invalidations over server-sent events. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return recent traffic buckets and path events for an edge. */
        get: operations["getEdgeHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return canonical nodes with traffic in a fixed history window. */
        get: operations["getHistoryNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a keyset-paginated page of logical traffic edges. */
        get: operations["listHistoryEdges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ServerCapabilities: {
            observerProtocolVersions: number[];
            features: string[];
        };
        DeviceDirectory: {
            sync: components["schemas"]["DirectorySyncState"];
            devices: components["schemas"]["DirectoryDevice"][];
        };
        DirectorySyncState: {
            /** @enum {string} */
            status: "disabled" | "syncing" | "healthy" | "stale";
            /** Format: date-time */
            lastAttemptAt?: string;
            /** Format: date-time */
            lastSuccessAt?: string;
            /** Format: date-time */
            nextRetryAt?: string;
            /** @enum {string} */
            errorCode?: "unauthorized" | "forbidden" | "rate-limited" | "unavailable" | "timeout" | "invalid-response";
            invalidAddressCount: number;
        };
        DirectoryDevice: {
            id: string;
            stableNodeId: string;
            dnsName?: string;
            hostname?: string;
            platform?: string;
            tailscaleIps: string[];
            tags: string[];
            connectedToControl: boolean;
            /** Format: date-time */
            lastSeen?: string;
            /** Format: date-time */
            collectedAt: string;
            runtime?: components["schemas"]["DirectoryRuntimeEvidence"];
            identityStatus: components["schemas"]["IdentityStatus"];
            conflicts: components["schemas"]["MetadataConflict"][];
        };
        DirectoryRuntimeEvidence: {
            dnsName?: string;
            hostname?: string;
            platform?: string;
            tailscaleIps: string[];
            observable: boolean;
            online: boolean;
            /** Format: date-time */
            lastEvidenceAt: string;
            /** Format: date-time */
            collectedAt: string;
        };
        MetadataConflict: {
            /** @enum {string} */
            field: "dnsName" | "hostname" | "os" | "tailscaleIps";
            directoryValues: string[];
            runtimeValues: string[];
            /** Format: date-time */
            directoryCollectedAt: string;
            /** Format: date-time */
            runtimeCollectedAt: string;
        };
        DirectoryEnrichment: {
            stableNodeId: string;
            dnsName?: string;
            hostname?: string;
            os?: string;
            tailscaleIps: string[];
            tags: string[];
            connectedToControl: boolean;
            /** Format: date-time */
            lastSeen?: string;
            /** Format: date-time */
            collectedAt: string;
            conflicts: components["schemas"]["MetadataConflict"][];
        };
        /** @description Normal observer messages contain observers. observer_withdrawal contains observer identities without peers. relay_session_update contains relaySessions instead; the server rejects envelopes that mix the forms. */
        ReportEnvelope: {
            /** @constant */
            version: 1;
            /** Format: uuid */
            reportId: string;
            /** Format: uuid */
            reporterInstanceId: string;
            /** Format: int64 */
            sequence: number;
            /** Format: date-time */
            collectedAt: string;
            kind: components["schemas"]["ReportKind"];
            observers?: components["schemas"]["ObserverReport"][];
            relaySessions?: components["schemas"]["RelaySessionObservation"][];
        };
        /** @enum {string} */
        ReportKind: "observer_hello" | "inventory_update" | "traffic_sample" | "observer_heartbeat" | "observer_withdrawal" | "relay_session_update";
        /** @description For hello and inventory_update, peers is the observer's complete current runtime peer view. For traffic_sample it is sparse and contains only peers with business byte deltas. observer_withdrawal forbids peers. collectedAt is the time for this observer inside a multi-observer envelope; legacy reports may omit it and use the envelope timestamp. */
        ObserverReport: {
            observer: components["schemas"]["NodeIdentity"];
            inventoryGeneration: string;
            /** Format: date-time */
            collectedAt?: string;
            peers?: components["schemas"]["PeerObservation"][];
        };
        /** @description At least one stableNodeId, nodeId, nodeKey, discoKey, or Tailscale IP is required. Names are display fields and never merge nodes. */
        NodeIdentity: {
            stableNodeId?: string;
            nodeId?: string;
            nodeKey?: string;
            discoKey?: string;
            hostname?: string;
            dnsName?: string;
            /** @description Reported operating system for display only; never identity evidence. */
            os?: string;
            tailscaleIps?: string[];
        };
        PeerObservation: {
            peer: components["schemas"]["NodeIdentity"];
            /** Format: int64 */
            rxBytes: number;
            /** Format: int64 */
            txBytes: number;
            /** Format: int64 */
            rxDelta: number;
            /** Format: int64 */
            txDelta: number;
            /**
             * Format: int64
             * @description Zero for hello/inventory baselines; positive for traffic samples.
             */
            sampleDurationMs: number;
            path: components["schemas"]["PathObservation"];
            /** Format: date-time */
            lastActive: string;
        };
        /** @description A Peer Relay observer's view of traffic between two Tailnet nodes. The logical edge is source-target while relay supplies third-party provenance. */
        RelaySessionObservation: {
            /** @description The relay observer; stableNodeId is required by the ingest contract. */
            relay: components["schemas"]["NodeIdentity"];
            source: components["schemas"]["RelaySessionClient"];
            target: components["schemas"]["RelaySessionClient"];
            sessionId: string;
            /** Format: int64 */
            vni: number;
            /** Format: int64 */
            sourceToTargetBytes: number;
            /** Format: int64 */
            targetToSourceBytes: number;
            /** Format: int64 */
            sourceToTargetDelta: number;
            /** Format: int64 */
            targetToSourceDelta: number;
            /** Format: int64 */
            sampleDurationMs: number;
            /** Format: date-time */
            lastActive: string;
        };
        /** @description One endpoint of a relay session. sessionClientId, discoShort, and endpoint are scoped hints and never global canonical identity aliases. */
        RelaySessionClient: {
            sessionClientId: string;
            identity?: components["schemas"]["NodeIdentity"];
            discoShort?: string;
            /** @description Current underlay endpoint; accepted only as volatile provenance. */
            endpoint?: string;
        };
        /** @enum {string} */
        IdentityStatus: "resolved" | "partial" | "anonymous" | "conflict";
        PathObservation: {
            kind: components["schemas"]["PathKind"];
            directEndpoint?: string;
            derpRegion?: string;
            peerRelayStableNodeId?: string;
            /** Format: int64 */
            peerRelayVni?: number;
        };
        /** @enum {string} */
        PathKind: "direct" | "derp" | "peer_relay" | "unknown";
        ReportReceipt: {
            accepted: boolean;
            resyncRequired: boolean;
            controlStableNodeIds: string[];
            /** Format: int64 */
            heartbeatIntervalMs: number;
        };
        Topology: {
            /** Format: date-time */
            generatedAt: string;
            /**
             * Format: date-time
             * @description Earliest known lifecycle deadline that can change this snapshot.
             */
            nextChangeAt?: string;
            nodes: components["schemas"]["TopologyNode"][];
            edges: components["schemas"]["TopologyEdge"][];
            observers: components["schemas"]["ObserverState"][];
        };
        TopologyNode: components["schemas"]["NodeIdentity"] & {
            id: string;
            observable: boolean;
            online: boolean;
            /** Format: date-time */
            lastEvidenceAt: string;
            clockSkewed: boolean;
            identityStatus?: components["schemas"]["IdentityStatus"];
            directory?: components["schemas"]["DirectoryEnrichment"];
        };
        TopologyEdge: {
            id: string;
            source: string;
            target: string;
            /** @description True when either endpoint is the dedicated Tailpath control identity. */
            systemTelemetry: boolean;
            path: components["schemas"]["PathObservation"];
            /** @enum {string} */
            state: "active" | "recent";
            /** Format: double */
            aToBBytesPerSecond: number;
            /** Format: double */
            bToABytesPerSecond: number;
            /** Format: date-time */
            lastActive: string;
            observations: components["schemas"]["ObservationProvenance"][];
            conflicts?: components["schemas"]["PathObservation"][];
        };
        ObservationProvenance: {
            observerId: string;
            path: components["schemas"]["PathObservation"];
            /** Format: date-time */
            collectedAt: string;
            /** Format: date-time */
            receivedAt: string;
            clockSkewed: boolean;
            relaySession?: components["schemas"]["RelaySessionProvenance"];
        };
        /** @description Sanitized third-party provenance; underlay endpoints are never exposed. */
        RelaySessionProvenance: {
            sessionId: string;
            /** Format: int64 */
            vni: number;
            sourceIdentityStatus: components["schemas"]["IdentityStatus"];
            targetIdentityStatus: components["schemas"]["IdentityStatus"];
        };
        ObserverState: {
            id: string;
            hostname: string;
            online: boolean;
            /** Format: date-time */
            lastSeen: string;
            /** Format: date-time */
            lastCollectedAt: string;
            /** Format: int64 */
            clockSkewMs: number;
            clockSkewed: boolean;
        };
        EdgeHistory: {
            edgeId: string;
            source: components["schemas"]["HistoryNodeReference"];
            target: components["schemas"]["HistoryNodeReference"];
            systemTelemetry: boolean;
            relatedNodes: components["schemas"]["HistoryNodeReference"][];
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: int64 */
            bucketDurationMs: number;
            /**
             * Format: date-time
             * @description Exact server-received time of the last traffic in the selected window. Omitted when the window is empty.
             */
            lastTrafficAt?: string;
            traffic: components["schemas"]["TrafficBucket"][];
            pathAnchor?: components["schemas"]["PathEvent"];
            pathEvents: components["schemas"]["PathEvent"][];
            trafficTruncated: boolean;
            pathEventsTruncated: boolean;
        };
        /** @enum {string} */
        HistoryWindow: "15m" | "1h" | "6h" | "24h" | "7d";
        HistoryNodeReference: {
            id: string;
            stableNodeId?: string;
            label: string;
            hostname?: string;
            dnsName?: string;
            os?: string;
            identityStatus?: components["schemas"]["IdentityStatus"];
        };
        HistoryNodes: {
            nodes: components["schemas"]["HistoryNodeReference"][];
        };
        HistoryEdgeSummary: {
            edgeId: string;
            source: components["schemas"]["HistoryNodeReference"];
            target: components["schemas"]["HistoryNodeReference"];
            systemTelemetry: boolean;
            /** Format: date-time */
            lastTrafficAt: string;
            /** Format: int64 */
            aToBBytes: number;
            /** Format: int64 */
            bToABytes: number;
            paths: components["schemas"]["PathKind"][];
        };
        HistoryEdgePage: {
            edges: components["schemas"]["HistoryEdgeSummary"][];
            nextCursor?: string;
        };
        TrafficBucket: {
            /** Format: date-time */
            bucketStart: string;
            /** Format: int64 */
            aToBBytes: number;
            /** Format: int64 */
            bToABytes: number;
        };
        PathEvent: {
            /** Format: date-time */
            observedAt: string;
            path: components["schemas"]["PathObservation"];
            conflicts: components["schemas"]["PathObservation"][];
            observations: components["schemas"]["ObservationProvenance"][];
        };
        Problem: {
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: {
        /** @description Request failed. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        HistoryWindow: components["schemas"]["HistoryWindow"];
        /** @description Include Tailpath control-plane telemetry for explicit diagnostics. */
        IncludeSystemTelemetry: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server capabilities available to trusted reporters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerCapabilities"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    submitReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportEnvelope"];
            };
        };
        responses: {
            /** @description Report accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getTopology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current topology. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topology"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current full directory snapshot and synchronization state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDirectory"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getEdgeHistory: {
        parameters: {
            query: {
                window: components["parameters"]["HistoryWindow"];
                /** @description Include Tailpath control-plane telemetry for explicit diagnostics. */
                includeSystemTelemetry?: components["parameters"]["IncludeSystemTelemetry"];
            };
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Edge history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeHistory"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getHistoryNodes: {
        parameters: {
            query: {
                window: components["parameters"]["HistoryWindow"];
                /** @description Include Tailpath control-plane telemetry for explicit diagnostics. */
                includeSystemTelemetry?: components["parameters"]["IncludeSystemTelemetry"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching canonical node references. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryNodes"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    listHistoryEdges: {
        parameters: {
            query: {
                window: components["parameters"]["HistoryWindow"];
                /** @description Include Tailpath control-plane telemetry for explicit diagnostics. */
                includeSystemTelemetry?: components["parameters"]["IncludeSystemTelemetry"];
                nodeId?: string;
                /** @description Match when the path appeared at any point in the window. */
                path?: components["schemas"]["PathKind"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching logical edge page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEdgePage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
}
